services:
  web:
    context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASS=dbpass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
