services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    command: >
      sh -c "daphne -b 0.0.0.0 -p 8000 backend.asgi:application"

    depends_on:
      - database
      - redis


  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
