# Generated by Django 5.2.2 on 2025-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_edit_key_note_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
